[package]
name = "klickhouse"
version = "0.2.1"
authors = ["Protryon <max.bruce12@gmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"
repository = "https://github.com/Protryon/klickhouse"
description = "Klickhouse is a pure Rust SDK for working with Clickhouse with the native protocol in async environments with minimal boilerplate and maximal performance."
keywords = [ "clickhouse", "database", "tokio", "sql" ]
readme = "../README.md"

[dependencies]
tokio = { version = "1", features = ["io-util", "net", "sync", "rt", "full"] }
async-trait = "0.1"
anyhow = "1.0"
log = "0.4"
indexmap = { version = "1.6" }
uuid = { version = "0.8", features = ["v4"], optional = true }
chrono = "0.4"
chrono-tz = "0.5"
futures = "0.3"
tokio-stream = "0.1"
lz4 = { version = "1.23", optional = true }
klickhouse_derive = { version = "=0.2.1", optional = true, path = "../klickhouse_derive" }
cityhash-rs = "1.0"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
env_logger = "0.6"

[features]
default = ["uuid", "derive", "compression"]
derive = ["klickhouse_derive"]
compression = ["lz4"]

[build-dependencies]
rustc_version = "0.3"
